<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>KeepPassword.Setup</RootNamespace>
    <AssemblyName>KeepPassword.Setup</AssemblyName>
    <ApplicationIcon>..\KeepPassword.App\Assets\app.ico</ApplicationIcon>
    <Version>0.2.0</Version>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\KeepPassword.App\Assets\logo.png" Link="Assets\logo.png" />
    <AvaloniaResource Include="..\KeepPassword.App\Assets\app.ico" Link="Assets\app.ico" />
  </ItemGroup>

  <ItemGroup Condition="Exists('payload.zip')">
    <EmbeddedResource Include="payload.zip" LogicalName="KeepPassword.Setup.payload.zip" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KeepPassword.Core\KeepPassword.Core.csproj" />
  </ItemGroup>

</Project>
